# Generated by Django 4.0.3 on 2022-06-12 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('coach', models.CharField(max_length=150)),
            ],
        ),
    ]
