# Generated by Django 4.0.3 on 2022-06-12 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definition', models.CharField(max_length=40, unique=True)),
                ('teams', models.ManyToManyField(to='scoreboard.team')),
            ],
        ),
    ]
