# Generated by Django 3.2.13 on 2022-06-15 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['coach'], 'verbose_name': 'Time', 'verbose_name_plural': 'Times'},
        ),
        migrations.AlterField(
            model_name='team',
            name='coach',
            field=models.CharField(default='Não informado', max_length=150),
        ),
    ]
