# Generated by Django 3.2.13 on 2022-06-15 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0002_auto_20220615_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='coach',
            field=models.CharField(default='Não informado', help_text='é o professor do time', max_length=150),
        ),
    ]
