# Generated by Django 3.2 on 2022-06-12 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0003_auto_20220612_0029'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='soccerplayer',
            options={'ordering': ['name'], 'verbose_name_plural': 'SoccerPlayers'},
        ),
        migrations.RemoveConstraint(
            model_name='soccerplayer',
            name='unique_team_name_number',
        ),
        migrations.AddConstraint(
            model_name='soccerplayer',
            constraint=models.UniqueConstraint(fields=('team', 'name', 'number'), name='unique_team_name_number_condition'),
        ),
    ]
