# Generated by Django 3.2.13 on 2022-06-15 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0003_alter_team_coach'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='coach',
            field=models.CharField(blank=True, help_text='é o professor do time', max_length=150, null=True),
        ),
    ]
