# Generated by Django 3.2.13 on 2022-06-22 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0006_auto_20220621_2347'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament', models.CharField(max_length=100)),
                ('goal_home', models.IntegerField(default=0)),
                ('goal_visiting', models.IntegerField(default=0)),
                ('date', models.DateTimeField()),
                ('team_home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_home_team', to='scoreboard.team')),
                ('team_visiting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_visiting_team', to='scoreboard.team')),
            ],
            options={
                'verbose_name_plural': 'Matchs',
                'ordering': ['-date'],
            },
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.UniqueConstraint(fields=('tournament', 'team_home', 'team_visiting'), name='unique_tournament_team_home_visiting'),
        ),
    ]
