# Generated by Django 3.2 on 2022-06-12 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0006_auto_20220612_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playgame',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoreboard.match'),
        ),
    ]
