# Generated by Django 3.2 on 2022-06-23 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0008_auto_20220622_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='coach',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
